// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmL2MmpK1xsngvGOuq2EsEE44TmQMnRXM',
    appId: '1:666810031995:android:5a7ffceea19bafe1b467de',
    messagingSenderId: '666810031995',
    projectId: 'fir-positive-content',
    storageBucket: 'fir-positive-content.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyDtWkYgiU_9vcdtgJOw7Ij8y-IwupnJ1xc",
      projectId: "fir-positive-content",
      storageBucket: "fir-positive-content.appspot.com",
      messagingSenderId: "666810031995",
      appId: "1:666810031995:web:d5ce3b8ea10050e3b467de"
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjbzrcVPXLYn_JdejulzKuNXWdYgwjOIE',
    appId: '1:666810031995:ios:b26be6fae331bab3b467de',
    messagingSenderId: '666810031995',
    projectId: 'fir-positive-content',
    storageBucket: 'fir-positive-content.appspot.com',
    iosClientId: '666810031995-gj2p1p03qj8617m2rl8j3s4dg58p8k5p.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );
}
